server:
  port: 8003

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bling_permission?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.bling.permission.model

# optional: 设置日志级别
#logging:
#  level:
#    root: info