spring:
  application:
    name: bling-permission-service

  config:
    import:
      - optional:nacos:bling-permission-service-dev.yaml

  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yaml
        namespace: 571b9102-43b9-492b-9c2a-8ed2455d2f1e
        group: group-dev
      discovery:
        server-addr: localhost:8848
        namespace: 571b9102-43b9-492b-9c2a-8ed2455d2f1e
        group: group-dev
