server:
  port: 8001

spring:
  application:
    name: bling-auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/bling_auth?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.bling.auth.model
