server:
  port: 8002

spring:
  application:
    name: bling-user-service

  config:
    import:
      - optional:nacos:bling-common.yaml
      # - optional:nacos:bling-auth-service.yaml

  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yaml
        shared-configs:
          - dataId: bling-common.yaml
            refresh: true
      discovery:
        server-addr: localhost:8848

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.bling.auth.model